language: go

go:
  - 1.9.X
  - master

go_import_path:
  - github.com/JuiMin/HALP

before_install: ./servers/gateway/scripts/gencert.sh

env:
  - ADDR=":443" TLSCERT="/server/gateway/tls/fullchain.pem" TLSKEY="/server/gateway/tls/privkey.pem"
