language: go

sudo: false

go:
  - 1.9.X

before_install: 
  - go get github.com/mattn/goveralls

env:
  - ADDR=":443" TLSCERT="/server/gateway/tls/fullchain.pem" TLSKEY="/server/gateway/tls/privkey.pem" COVERALLS_TOKEN="pXG7s1nhA2iTD6qlq7P1A964rFmZetMRM"

script:
  - $GOPATH/bin/goveralls -service=travis-ci